name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage report
        run: npm run test -- --coverage

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2

      - name: Build
        run: npm run build
